dates1<-as.POSIXct(dates,format="%a %b %d %H:%M:%S PDT %Y", tz="America/Los_Angeles")
head(dates1)
DOW<-weekdays(dates1)
times1<-strftime(dates1, format="%H:%M:%S")
dates1<-as.Date(dates1)
dates2<-as.POSIXct(dates,format="%a %b %d %H:%M:%S PDT %Y", tz="America/Los_Angeles")
head(data)
final_data<-data.frame(data[,1], data[,3], dates2, dates1, times1, DOW, data[,4])
head(final_data)
names(final_data)<-c("Sentiment","Original.Poster","Full.Date","Date","Time","Day.Of.Week","Tweet")
head(final_data)
write.table(final_data, file="intermediateData.csv", col.names = FALSE, sep=",")